apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-game-deployment
spec:
  progressDeadlineSeconds: 60
  replicas: 2
  selector:
    matchLabels:
      app: nginx-game
  strategy:
    rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-game
    spec:
      containers:
        - name: nginx-game
          image: testsysadmin8/nginx-game:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80